from .AggregateMatrix import AggregateMatrix as aggregate_matrix
from .DemuxEM import DemuxEM as demuxEM
from .Clustering import Clustering as cluster
from .DeAnalysis import DeAnalysis as de_analysis
from .AnnotateCluster import AnnotateCluster as annotate_cluster
from .Plotting import Plotting as plot
from .iPlotting import iPlotting as iplot
from .SubClustering import SubClustering as subcluster
from .View import View as view
from .ConvertMatrix import ConvertMatrix as convert_matrix
from .CITESeq import CITESeq as merge_rna_adt
from .CheckSampleIndexes import CheckSampleIndexes as check_indexes
from .FindMarkers import FindMarkers as find_markers
from .DownSample import DownSample as down_sample
