from .AggregateMatrix import AggregateMatrix as aggregate_matrix
from .Clustering import Clustering as cluster
from .DeAnalysis import DeAnalysis as de_analysis
from .AnnotateCluster import AnnotateCluster as annotate_cluster
from .Plotting import Plotting as plot
from .iPlotting import iPlotting as iplot
from .SubClustering import SubClustering as subcluster
from .View import View as view
from .SCPOutput import SCPOutput as scp_output
from .CITESeq import CITESeq as cite_seq
